# Generated by Django 4.0.5 on 2022-07-04 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("identifier", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("clean_name", models.CharField(max_length=100)),
                ("IBAN", models.CharField(max_length=40)),
                ("BIC", models.CharField(max_length=15)),
                ("is_supporter", models.BooleanField(default=False)),
                ("supporter_since", models.DateField(default=None, null=True)),
                ("not_supporter_since", models.DateField(default=None, null=True)),
                ("is_member", models.BooleanField(default=False)),
                ("member_since", models.DateField(default=None, null=True)),
                ("not_member_since", models.DateField(default=None, null=True)),
                ("support_amount", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="Purpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("valuta", models.DateField()),
                ("textkey", models.CharField(max_length=30)),
                ("comment", models.CharField(max_length=100)),
                ("currency", models.CharField(max_length=30)),
                ("signed", models.FloatField(max_length=30)),
                ("taxes", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cashviz.category",
                    ),
                ),
                (
                    "purpose",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cashviz.purpose",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cashviz.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("decided_date", models.DateField()),
                ("expire_date", models.DateField()),
                ("url", models.URLField()),
                (
                    "purpose",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cashviz.purpose",
                    ),
                ),
            ],
        ),
    ]
